# Project information
site_name: EPI Research Documentation
site_description: Documentation for EPI Research Department staff
site_url: https://economic.github.io/research_docs/

# Repository
repo_name: economic/research_docs
repo_url: https://github.com/economic/research_docs

theme:
  name: 'material'
  language: en
  feature:
    tabs: true
  palette:
    primary: 'blue grey'
    accent:  'indigo'
  font:
    text: Source Sans Pro
    code: Fira Code
  favicon: assets/images/favicon.png
  logo:
    icon: "home"

markdown_extensions:
  - codehilite
  - pymdownx.superfences

nav:
