# Project information
site_name: EPI Research Documentation
site_description: Documentation for EPI Research Department staff
site_url: https://economic.github.io/research_docs/
copyright: 'Copyright &copy; 2019 <a href= "https://epi.org">Economic Policy Institute</a>'

theme:
  name: 'material'
  language: en
  feature:
    tabs: true
  palette:
    primary: 'blue grey'
    accent:  'indigo'
  font:
    text: Source Sans Pro
    code: Fira Code
  favicon: assets/images/favicon.png
  logo:
    icon: "home"
  custom_dir: theme_customizations

markdown_extensions:
  - codehilite
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages

nav:
